#!/usr/bin/env python3
"""
CannGuide — Lexikon-Erweiterung v1.0
Im Repo-Root ausführen: python3 patch_lexikon_final.py
Idempotent — bereits gepatchte Stellen werden erkannt.
"""
import re, subprocess, sys, tempfile, os

src = open('index.html', encoding='utf-8').read()
changes = 0

# ── [0] Bekannter GPL-Header-Bug (falls noch nicht gepatcht) ──────────────
broken_js = 'var html = \'<!DOCTYPE html><html lang="de">\n<!-- CannGuide \u00a9 2024-2026 quack-tic\n     Licensed under GNU GPL v3 \u2014 https://github.com/quack-tic/CannGuide --><head>'
fixed_js  = 'var html = \'<!DOCTYPE html><html lang="de"><head>'
if broken_js in src:
    src = src.replace(broken_js, fixed_js)
    changes += 1; print('\u2714 [0] GPL-Header-Bug gefixt')
else:
    print('\u00b7 [0] GPL-Header-Bug (bereits gepatcht)')

# ── [1] CSS: neue Tag-Klassen med (blau) + bio (lila) ────────────────────
OLD_CSS = '.lex-tag.base{background:var(--amber-bg);color:var(--amber);border-color:var(--amber)}'
NEW_CSS = '''.lex-tag.base{background:var(--amber-bg);color:var(--amber);border-color:var(--amber)}
.lex-tag.med{background:#0d1f2d;color:#4a9eda;border-color:#4a9eda}
.lex-tag.bio{background:#1a0d2e;color:#a78bfa;border-color:#a78bfa}'''
if OLD_CSS in src:
    src = src.replace(OLD_CSS, NEW_CSS); changes += 1; print('\u2714 [1] CSS: neue Tags med + bio')
elif '.lex-tag.med{' in src:
    print('\u00b7 [1] CSS (bereits gepatcht)')
else:
    print('\u2718 [1] CSS-Muster nicht gefunden!')

# ── [2] renderLib: neue Tabs ──────────────────────────────────────────────
OLD_RENDER = "var cats = {loesungsmittel:'L\u00f6sungsmittel', tricks:'Profi-Tricks', dekarb:'Dekarboxylierung', fehler:'Troubleshooting', lexikon:'\U0001f4d6 Lexikon'};"
NEW_RENDER = "var cats = {loesungsmittel:'L\u00f6sungsmittel', tricks:'Profi-Tricks', dekarb:'Dekarboxylierung', fehler:'Troubleshooting', extrakte:'\U0001f537 Extrakte', cannabinoide:'\U0001f9ea Cannabinoide', ecs:'\U0001f52c ECS', botanik:'\U0001f33f Botanik', produkte:'\U0001f343 Produkte', konsum:'\U0001f4a8 Konsum', grow:'\U0001f331 Anbau', medizin:'\U0001f48a Medizin', risiken:'\u26a0\ufe0f Risiken', szene:'\U0001f4d6 Szene'};"
if OLD_RENDER in src:
    src = src.replace(OLD_RENDER, NEW_RENDER); changes += 1; print('\u2714 [2] renderLib: 9 neue Tabs')
elif 'cannabinoide:' in src:
    print('\u00b7 [2] renderLib (bereits gepatcht)')
else:
    print('\u2718 [2] renderLib-Muster nicht gefunden!')

# ── [3] LIB-Key: lexikon → extrakte ──────────────────────────────────────
OLD_KEY = "  lexikon:{cat:'Lexikon \u2014 Extrakt-Begriffe',items:["
NEW_KEY = "  extrakte:{cat:'Extrakt-Begriffe & Konzentrate',items:["
if OLD_KEY in src:
    src = src.replace(OLD_KEY, NEW_KEY); changes += 1; print('\u2714 [3] LIB-Key: lexikon \u2192 extrakte')
elif "  extrakte:{cat:'Extrakt-Begriffe" in src:
    print('\u00b7 [3] LIB-Key (bereits gepatcht)')
else:
    print('\u2718 [3] LIB-Key-Muster nicht gefunden!')

# ── [4] Neue Kategorien anhängen ─────────────────────────────────────────
OLD_END = "THCA\u2192THC, CBDA\u2192CBD durch Hitze. Pflicht f\u00fcr alle Edibles.'}\n  ]}\n};"
if 'cannabinoide:{cat:' in src:
    print('\u00b7 [4] Neue Kategorien (bereits vorhanden)')
elif OLD_END in src:
    NEW_CATS = """,
  cannabinoide:{cat:'Cannabinoide & Wirkstoffe',items:[
    {t:'THC / Delta-9-Tetrahydrocannabinol',b:'<span class="lex-term">THC</span><span class="lex-tag conc">Hauptwirkstoff</span><span class="lex-tag adv">Psychoaktiv</span><br>THC ist der prim\u00e4re psychoaktive Wirkstoff der Cannabispflanze und verantwortlich f\u00fcr das \\"High\\". Es bindet vor allem an CB1-Rezeptoren im Gehirn und beeinflusst Wahrnehmung, Stimmung, Ged\u00e4chtnis und Koordination. Medizinisch wird THC u.a. bei \u00dcbelkeit, Schmerzen und Appetitverlust eingesetzt. <b>Wichtig f\u00fcr Edibles:</b> In der Leber entsteht aus THC das deutlich st\u00e4rkere 11-Hydroxy-THC \u2014 weshalb Edibles bei gleicher Dosis intensiver und l\u00e4nger wirken als Inhalation.'},
    {t:'CBD / Cannabidiol',b:'<span class="lex-term">CBD</span><span class="lex-tag conc">Cannabinoid</span><span class="lex-tag base">Nicht psychoaktiv</span><br>CBD ist das mengenmässig zweith\u00e4ufigste Cannabinoid und wirkt nicht berauschend. Es kann die psychoaktive Wirkung von THC abschw\u00e4chen und zeigt entz\u00fcndungshemmende, angstl\u00f6sende und krampfl\u00f6sende Eigenschaften. F\u00fcr Konsumenten mit Angstneigung oder niedriger Toleranz k\u00f6nnen CBD-reiche Sorten das Risiko unangenehmer Erfahrungen reduzieren. Das Medikament Epidiolex (reines CBD) ist zur Behandlung schwerer Epilepsieformen zugelassen.'},
    {t:'THCA / THC-S\u00e4ure',b:'<span class="lex-term">THCA</span><span class="lex-tag conc">Vorstufe</span><br>THCA ist die nat\u00fcrliche, nicht-psychoaktive Vorstufe von THC in der frischen Pflanze. Erst durch Dekarboxylierung (Erhitzen) wird THCA in aktives THC umgewandelt. Rohes Cannabis enth\u00e4lt kaum THC, daf\u00fcr viel THCA \u2014 frisches Pflanzenmaterial berauscht beim Essen deshalb nicht. F\u00fcr Edibles ist eine vollst\u00e4ndige Dekarboxylierung zwingend notwendig.'},
    {t:'CBDA / CBD-S\u00e4ure',b:'<span class="lex-term">CBDA</span><span class="lex-tag conc">Vorstufe</span><br>CBDA ist die Vorstufe von CBD in der rohen Pflanze und wird erst durch Hitze in CBD umgewandelt. In Rohkost-Cannabis-Produkten (frisch gepresste S\u00e4fte) bleibt CBDA erhalten. Aktuelle Forschung deutet auf eigenst\u00e4ndige entz\u00fcndungshemmende Eigenschaften von CBDA hin, die sich von CBD unterscheiden.'},
    {t:'11-Hydroxy-THC (11-OH-THC)',b:'<span class="lex-term">11-OH-THC</span><span class="lex-tag conc">Metabolit</span><span class="lex-tag adv">Edibles-Risiko</span><br>11-Hydroxy-THC entsteht in der Leber, wenn THC oral aufgenommen wird. Es ist deutlich st\u00e4rker psychoaktiv als Delta-9-THC und \u00fcberquert die Blut-Hirn-Schranke effizienter. Das erkl\u00e4rt, warum Edibles trotz gleicher THC-Menge intensiver und l\u00e4nger wirken als inhaliertes Cannabis. <b>Der Onset betr\u00e4gt 30\u2013120 Minuten</b> \u2014 wer zu fr\u00fch nachdosiert, riskiert eine massive \u00dcberdosierung.'},
    {t:'CBN / Cannabinol',b:'<span class="lex-term">CBN</span><span class="lex-tag conc">Cannabinoid</span><br>CBN entsteht durch Oxidation und Abbau von THC \u2014 es ist ein Alterungsprodukt. Altes oder schlecht gelagertes Cannabis enth\u00e4lt h\u00f6here CBN-Mengen, weshalb die Wirkung milder und sedierender ausf\u00e4llt (etwa 10% der THC-St\u00e4rke). F\u00fcr die Praxis: gut gelagertes Cannabis in dunklen, luftdichten Beh\u00e4ltern bei Raumtemperatur bewahrt den THC-Gehalt am besten.'},
    {t:'CBG / Cannabigerol',b:'<span class="lex-term">CBG</span><span class="lex-tag conc">Cannabinoid</span><span class="lex-tag base">Muttercannabinoid</span><br>CBG gilt als \\"Muttercannabinoid\\" \u2014 aus CBGA werden alle anderen Cannabinoide biosynthetisiert. In reifen Bl\u00fcten ist CBG deshalb meist nur in Spuren vorhanden. CBG wirkt nicht berauschend und wird auf antibakterielle, entz\u00fcndungshemmende und neuroprotektive Eigenschaften hin erforscht.'},
    {t:'CBC / Cannabichromen',b:'<span class="lex-term">CBC</span><span class="lex-tag conc">Cannabinoid</span><br>CBC ist ein nicht-psychoaktives Cannabinoid mit entz\u00fcndungshemmenden und antidepressiven Eigenschaften in Tiermodellen. Es bindet nur schwach an CB1/CB2, interagiert aber mit TRPV1- und TRPA1-Rezeptoren. CBC tr\u00e4gt zum Entourage-Effekt bei und ist besonders in frischem Pflanzenmaterial vorhanden.'},
    {t:'THCV / Tetrahydrocannabivarin',b:'<span class="lex-term">THCV</span><span class="lex-tag conc">Cannabinoid</span><br>THCV ist strukturell \u00e4hnlich wie THC, hat aber je nach Dosis gegens\u00e4tzliche Wirkungen: In niedrigen Dosen blockiert es THC-Rezeptoren (antagonistisch), in hohen Dosen wirkt es THC-\u00e4hnlich. Sorten mit hohem THCV-Anteil stammen oft aus Afrika (z.B. Durban Poison).'},
    {t:'Delta-8-THC',b:'<span class="lex-term">Delta-8-THC</span><span class="lex-tag conc">Cannabinoid</span><span class="lex-tag adv">Grauzone</span><br>Delta-8-THC ist ein Isomer von Delta-9-THC mit \u00e4hnlicher, aber milderer psychoaktiver Wirkung. Kommerziell erh\u00e4ltliches Delta-8 wird meist synthetisch aus CBD hergestellt \u2014 dieser Prozess kann problematische Nebenprodukte erzeugen. Im DACH-Raum ist der Rechtsstatus unklar, viele Produkte bewegen sich in einer regulatorischen Grauzone. Ohne Labortest ist die Zusammensetzung nicht verifizierbar.'},
    {t:'THC-COOH (Nachweis)',b:'<span class="lex-term">THC-COOH</span><span class="lex-tag conc">Abbauprodukt</span><br>THC-COOH ist das finale Abbauprodukt von THC im K\u00f6rper und im Urin nachweisbar. Es ist nicht psychoaktiv, bleibt aber je nach Konsumh\u00e4ufigkeit 3\u201330 Tage (bei starken Konsumenten bis 90 Tage) nachweisbar. Drogentests messen THC-COOH, nicht THC selbst \u2014 ein positiver Test sagt daher nichts \u00fcber aktuelle Intoxikation aus.'},
    {t:'Terpene',b:'<span class="lex-term">Terpene</span><span class="lex-tag base">Aromastoffe</span><br>Terpene sind aromatische Verbindungen der Cannabispflanze \u2014 \u00fcber 200 wurden nachgewiesen. Sie interagieren mit Cannabinoiden und modulieren deren Wirkung (Entourage-Effekt). Wichtige Terpene: Myrcen (erdig, sedierend), Limonen (zitrusartig, stimmungsaufhellend), Linalool (lavendelartig, angstl\u00f6send), \u03b1-Pinen (Wald, Alertheit), \u03b2-Caryophyllen (pfeffrig, entz\u00fcndungshemmend). Bei der Extraktion gehen viele Terpene durch Hitze verloren \u2014 Live-Resin und Rosin gelten deshalb als terpenreicher.'},
    {t:'Flavonoide',b:'<span class="lex-term">Flavonoide</span><span class="lex-tag base">Pflanzenstoffe</span><br>Flavonoide sind sekund\u00e4re Pflanzenstoffe in Cannabis. Cannabis-spezifische Cannflavine A und B zeigen in Studien entz\u00fcndungshemmende Wirkung \u2014 bis zu 30\u00d7 st\u00e4rker als Aspirin. Flavonoide tragen zur Farbe der Pflanze bei (z.B. Purpurt\u00f6ne) und erg\u00e4nzen den Entourage-Effekt.'}
  ]},
  ecs:{cat:'Endocannabinoid-System',items:[
    {t:'Endocannabinoid-System (ECS)',b:'<span class="lex-term">ECS</span><span class="lex-tag base">K\u00f6rpereigenes System</span><br>Das ECS ist ein k\u00f6rpereigenes Signalsystem, das Prozesse wie Stimmung, Schlaf, Appetit, Schmerzempfinden und Immunfunktion reguliert. Es besteht aus Rezeptoren (CB1, CB2), k\u00f6rpereigenen Liganden (Endocannabinoide) und Enzymen zum Ab- und Aufbau. Cannabis wirkt, weil Phytocannabinoide an denselben Rezeptoren andocken wie k\u00f6rpereigene Substanzen. Das ECS wurde erst in den 1990ern entdeckt \u2014 die Forschung steht noch am Anfang.'},
    {t:'CB1-Rezeptor',b:'<span class="lex-term">CB1</span><span class="lex-tag base">Rezeptor</span><br>CB1-Rezeptoren konzentrieren sich im zentralen Nervensystem \u2014 in Hirnregionen f\u00fcr Ged\u00e4chtnis (Hippocampus), Koordination (Kleinhirn), Schmerzwahrnehmung und Emotionsregulation. THC bindet stark an CB1 und erzeugt so die psychoaktiven Effekte. Die Dichte von CB1 im Hirnstamm (Atemzentrum) ist gering \u2014 weshalb eine t\u00f6dliche \u00dcberdosis allein durch Cannabis pharmakologisch praktisch nicht m\u00f6glich ist.'},
    {t:'CB2-Rezeptor',b:'<span class="lex-term">CB2</span><span class="lex-tag base">Rezeptor</span><br>CB2-Rezeptoren finden sich haupts\u00e4chlich im Immunsystem \u2014 in Milz, Knochenmark und peripheren Immunzellen. Sie regulieren Entz\u00fcndungsreaktionen und sind kaum im Gehirn vertreten. CBD und CBG binden st\u00e4rker an CB2 als THC. CB2-Aktivierung ist ein wichtiger Ansatzpunkt f\u00fcr cannabis-basierte Medikamente ohne psychoaktive Wirkung.'},
    {t:'Anandamid',b:'<span class="lex-term">Anandamid</span><span class="lex-tag base">Endocannabinoid</span><br>Anandamid (Sanskrit: \\"Ananda\\" = Gl\u00fcckseligkeit) ist das wichtigste k\u00f6rpereigene Endocannabinoid. Es wird bei Schmerz, Stress und nach k\u00f6rperlicher Aktivit\u00e4t ausgesch\u00fcttet \u2014 mitverantwortlich f\u00fcr das \\"Runner\\'s High\\". Anandamid wirkt kurzlebig und wird schnell durch das Enzym FAAH abgebaut. THC verdr\u00e4ngt Anandamid von seinen Rezeptoren und imitiert dessen Wirkung, bleibt aber deutlich l\u00e4nger aktiv.'},
    {t:'2-Arachidonylglycerol (2-AG)',b:'<span class="lex-term">2-AG</span><span class="lex-tag base">Endocannabinoid</span><br>2-AG ist das mengenmässig h\u00e4ufigste Endocannabinoid im K\u00f6rper. Es bindet an CB1- und CB2-Rezeptoren und spielt eine wichtige Rolle bei Entz\u00fcndungsprozessen und synaptischer Plastizit\u00e4t. Im Gegensatz zu Anandamid wirkt 2-AG als vollst\u00e4ndiger Agonist an CB1 und wird durch das Enzym MAGL abgebaut.'}
  ]},
  botanik:{cat:'Botanik & Pflanzenkunde',items:[
    {t:'Cannabis sativa / indica / ruderalis',b:'<span class="lex-term">Cannabis-Arten</span><span class="lex-tag bio">Botanik</span><br>Cannabis sativa und Cannabis indica sind die zwei Haupttypen \u2014 die botanische Abgrenzung ist wissenschaftlich umstritten, da die meisten modernen Sorten Hybride sind. Sativa-Typen werden mit anregendem \\"Kopf-High\\" assoziiert, Indica-Typen mit entspannendem \\"K\u00f6rper-High\\". Diese Vereinfachung greift zu kurz: Tats\u00e4chlich bestimmt das Cannabinoid- und Terpen-Profil die Wirkung. Cannabis ruderalis ist eine kurzw\u00fcchsige Wildform aus Zentralasien, die autoflowering-Genetiken in die Zucht eingebracht hat.'},
    {t:'Trichome',b:'<span class="lex-term">Trichome</span><span class="lex-tag bio">Botanik</span><span class="lex-tag base">Harzdr\u00fcsen</span><br>Trichome sind kleine Harzdr\u00fcsen auf der Oberfl\u00e4che der Cannabisbl\u00fcten. Sie produzieren und speichern Cannabinoide, Terpene und Flavonoide. Reifegrad: klar = unreif, milchig-tr\u00fcb = maximales THC, bernsteinfarben = THC degradiert zu CBN (sedierender). Optimal f\u00fcr die Ernte: Mix aus 70\u201390% tr\u00fcb und 10\u201330% bernsteinfarben. Beurteilung mit 60\u00d7-Lupe oder Digitalmikroskop.'},
    {t:'Sinsemilla',b:'<span class="lex-term">Sinsemilla</span><span class="lex-tag bio">Botanik</span><br>Sinsemilla (Spanisch: \\"sin semilla\\" = ohne Samen) bezeichnet unbefruchtet gebliebene weibliche Cannabisbl\u00fcten. Durch Entfernen m\u00e4nnlicher Pflanzen vor der Bl\u00fcte wird Best\u00e4ubung verhindert \u2014 die Pflanze investiert Energie in Harzproduktion statt Samenbildung. Ergebnis: deutlich h\u00f6herer Wirkstoffgehalt, keine Samen. Praktisch alles heute erh\u00e4ltliche Marihuana ist Sinsemilla.'},
    {t:'Phytocannabinoide',b:'<span class="lex-term">Phytocannabinoide</span><span class="lex-tag bio">Botanik</span><br>\u00dcber 100 verschiedene Cannabinoide wurden in der Cannabispflanze nachgewiesen. In der rohen Pflanze liegen sie \u00fcberwiegend als S\u00e4ureformen vor (THCA, CBDA), die erst durch Hitze (Dekarboxylierung) in die aktiven Formen umgewandelt werden. Phytocannabinoide docken an denselben Rezeptoren an wie k\u00f6rpereigene Endocannabinoide.'}
  ]},
  produkte:{cat:'Produkte & Zubereitungsformen',items:[
    {t:'Marihuana / Cannabiskraut',b:'<span class="lex-term">Marihuana</span><span class="lex-tag base">Grundprodukt</span><br>Marihuana bezeichnet getrocknete Bl\u00fcten und Bl\u00e4tter der weiblichen Cannabispflanze \u2014 weltweit die verbreitetste Konsumform. THC-Gehalt variiert von unter 5% bis \u00fcber 30%. Beim Kauf auf dem Schwarzmarkt ist die Zusammensetzung unbekannt \u2014 eine zuverl\u00e4ssige Dosierung ist nicht m\u00f6glich. Legale Apothekensorten haben zertifizierte Gehaltsangaben.'},
    {t:'Haschisch / Cannabisharz',b:'<span class="lex-term">Haschisch</span><span class="lex-tag base">Harzprodukt</span><br>Haschisch wird durch Sammeln und Pressen der Trichome hergestellt \u2014 durch Sieben (Kief) oder Reiben mit der Hand (Charas). THC-Gehalt typischerweise 15\u201340%. Streckung mit Bindemitteln ist auf dem Schwarzmarkt weit verbreitet und f\u00fchrt zu unberechenbarer Wirkung.'},
    {t:'Charas',b:'<span class="lex-term">Charas</span><span class="lex-tag base">Traditionell</span><br>Charas ist handgeriebenes Haschisch aus dem indischen Subkontinent (Himalaya-Region). Die Bl\u00fcten werden zwischen den Handfl\u00e4chen gerieben, bis sich das Harz zu einer klebrigen Masse formt. Untrennbar mit dem Shiva-Kult des Hinduismus verbunden. Bekannte Herkünfte: Malana Cream, Kashmiri Charas.'},
    {t:'Kief / Drysift',b:'<span class="lex-term">Kief</span><span class="lex-tag base">Trichomprodukt</span><br>Kief bezeichnet durch Sieben gewonnene lose Trichomk\u00f6pfe \u2014 die reinste l\u00f6sungsmittelfreie Form. Enth\u00e4lt 30\u201360% THC und kann direkt konsumiert oder zu Haschisch gepresst werden. Mehrfaches Sieben durch feinere Siebe erh\u00f6ht Reinheit und Potenz.'},
    {t:'Edibles',b:'<span class="lex-term">Edibles</span><span class="lex-tag base">Essbar</span><span class="lex-tag adv">Dosierung beachten</span><br>Edibles sind cannabishaltige Lebensmittel \u2014 von Butter und \u00d6l \u00fcber Backwaren bis zu Gummib\u00e4rchen. Wirkungseintritt: 30\u2013120 Minuten. Wirkungsdauer: 4\u20138 Stunden. <b>Gr\u00f6sste Gefahr:</b> Nachdosieren bevor die Wirkung sp\u00fcrbar ist. Regel: mit 2,5\u20135 mg THC starten, mindestens 2 Stunden warten.'},
    {t:'Cannabisbutter / Cannabisr\u00f6l',b:'<span class="lex-term">Cannabisbutter</span><span class="lex-tag base">Infusion</span><br>Cannabisbutter und -\u00f6le sind Grundstoffe f\u00fcr selbsthergestellte Edibles. THC bindet an Fett \u2014 deshalb funktioniert die Extraktion in Butter, Kokos\u00f6l oder MCT-\u00d6l. Voraussetzung ist vollst\u00e4ndige Dekarboxylierung vor der Infusion. Die Wirkst\u00e4rke ist ohne Labortest kaum exakt bestimmbar \u2014 ein wesentlicher Risikofaktor f\u00fcr die Dosierung.'},
    {t:'Tinktur (Alkohol-Extrakt)',b:'<span class="lex-term">Tinktur</span><span class="lex-tag base">Extrakt</span><br>Tinkturen sind Alkohol-basierte Cannabis-Extrakte zur sublingualen Einnahme. Onset sublingual: 15\u201345 Minuten. Bei Schlucken wirken sie wie Edibles \u2014 langsamerer Onset durch Leberpassage. <b>Wichtig:</b> Ausschliesslich Lebensmittelethanol (mind. 90%) verwenden \u2014 Isopropanol und technische Alkohole sind giftig.'}
  ]},
  konsum:{cat:'Konsum & Methoden',items:[
    {t:'Inhalation \u2014 Grundlagen',b:'<span class="lex-term">Inhalation</span><span class="lex-tag base">Konsummethode</span><br>Bei der Inhalation gelangen Cannabinoide \u00fcber die Lungen direkt ins Blut. Wirkungseintritt: 30\u201390 Sekunden, Peak: 10\u201330 Minuten, Dauer: 1\u20133 Stunden. Im Vergleich zu Edibles ist die Wirkung k\u00fcrzer und besser steuerbar. Beim Verbrennen entstehen Verbrennungsprodukte wie Benzol, Kohlenmonoxid und Teer \u2014 \u00e4hnlich wie beim Tabakrauchen.'},
    {t:'Joint / Spliff',b:'<span class="lex-term">Joint</span><span class="lex-tag base">Konsummethode</span><br>Der Joint ist die verbreitetste Konsumform \u2014 Cannabis in Zigarettenpapier gerollt, oft mit Tabak gemischt (Spliff). Der Tabakzusatz erh\u00f6ht das Abh\u00e4ngigkeitspotenzial durch Nikotin erheblich. Pur-Joints ohne Tabak mit Aktivkohlefilter reduzieren den Schadstoffeintrag.'},
    {t:'Vaporizer / Verdampfer',b:'<span class="lex-term">Vaporizer</span><span class="lex-tag base">Konsummethode</span><br>Vaporizer erhitzen Cannabis auf 160\u2013220\u00b0C \u2014 unterhalb der Verbrennungstemperatur. Das erzeugt ein Aerosol statt Rauch, mit deutlich weniger sch\u00e4dlichen Verbrennungsprodukten. Empfohlene Temperaturen: 170\u2013185\u00b0C (schonend, mehr Terpene), 190\u2013210\u00b0C (volle Wirkung). Medizinische Ger\u00e4te: Volcano Medic, Mighty Medic. Studien zeigen reduzierte Atemwegssymptome bei Vaporer-Nutzung.'},
    {t:'Bong / Wasserpfeife',b:'<span class="lex-term">Bong</span><span class="lex-tag base">Konsummethode</span><br>Die Bong leitet Rauch durch Wasser, was ihn k\u00fchlt und teilweise filtert. Sie erm\u00f6glicht grosse Z\u00fcge mit hoher THC-Aufnahme in kurzer Zeit \u2014 was das \u00dcberdosierungsrisiko erh\u00f6ht. Das Wasser filtert wasserl\u00f6sliche Schadstoffe, nicht aber fettl\u00f6sliche Verbrennungsprodukte. Regelm\u00e4ssiges Reinigen verhindert Schimmel- und Bakterienbildung.'},
    {t:'Dabbing',b:'<span class="lex-term">Dabbing</span><span class="lex-tag adv">Fortgeschritten</span><br>Dabbing bezeichnet das Verdampfen hochkonzentrierter Extrakte auf einer erhitzten Nail. Bei Temperaturen \u00fcber 450\u00b0C entstehen Benzol und andere Karzinogene aus Terpenen. Dabs liefern extrem hohe THC-Dosen in einem einzigen Atemzug \u2014 nur f\u00fcr Konsumenten mit hoher Toleranz geeignet. Einsteiger k\u00f6nnen starke Panikattacken oder Bewusstlosigkeit erleben.'},
    {t:'Valsalva-Man\u00f6ver',b:'<span class="lex-term">Valsalva-Man\u00f6ver</span><span class="lex-tag adv">Risiko</span><br>Einatmen und Pressen gegen geschlossene Atemwege in der falschen Annahme, mehr THC aufzunehmen. Tats\u00e4chlich ist die THC-Absorption in der Lunge nach 2\u20133 Sekunden abgeschlossen \u2014 l\u00e4ngeres Halten bringt keinen Mehreffekt. Das Man\u00f6ver erh\u00f6ht den intrathorakalen Druck und kann zu Pneumothorax (Lungenriss) und Ohnmacht f\u00fchren.'},
    {t:'Sublinguale Anwendung',b:'<span class="lex-term">Sublingual</span><span class="lex-tag base">Konsummethode</span><br>Bei der sublingualen Einnahme wird Cannabis (meist als Tinktur oder \u00d6l) unter die Zunge gegeben und \u00fcber die Mundschleimhaut aufgenommen. Onset: 15\u201345 Minuten \u2014 schneller als Edibles, langsamer als Inhalation. Besonders geeignet f\u00fcr medizinische Anwender. Schlucken statt Halten verz\u00f6gert den Onset erheblich.'}
  ]},
  grow:{cat:'Anbau & Grow',items:[
    {t:'Indoor / Outdoor / Gew\u00e4chshaus',b:'<span class="lex-term">Anbaumethoden</span><span class="lex-tag bio">Anbau</span><br>Indoor-Anbau unter Kunstlicht erm\u00f6glicht vollst\u00e4ndige Kontrolle \u2014 auf Kosten von Energie und Setup-Aufwand. Outdoor-Anbau nutzt nat\u00fcrliches Sonnenlicht, ist g\u00fcnstiger, aber vom Klima abh\u00e4ngig. Gew\u00e4chsh\u00e4user kombinieren beide Ans\u00e4tze. Indoor-Qualit\u00e4ten haben meist h\u00f6here THC-Gehalte und gleichm\u00e4ssigere Qualit\u00e4t.'},
    {t:'Trichomreife & Erntezeitpunkt',b:'<span class="lex-term">Trichomreife</span><span class="lex-tag bio">Anbau</span><br>Klar = unreif. Milchig-tr\u00fcb = maximaler THC-Gehalt, anregende Wirkung. Bernsteinfarben = THC degradiert zu CBN, sedierende Wirkung. Optimal: 70\u201390% tr\u00fcb und 10\u201330% bernsteinfarben. Beurteilt mit 60\u00d7-Lupe oder Digitalmikroskop.'},
    {t:'Hydrokultur',b:'<span class="lex-term">Hydrokultur</span><span class="lex-tag bio">Anbau</span><br>Anbau ohne Erde \u2014 Pflanzen wachsen in N\u00e4hrl\u00f6sung, getragen von Steinwolle, Perlite oder Kokossubstrat. Vorteile: schnelleres Wachstum, h\u00f6here Ertr\u00e4ge. Nachteile: h\u00f6herer technischer Aufwand. Systeme: DWC (Deep Water Culture), NFT (Nutrient Film Technique), Ebb & Flow.'},
    {t:'Sinsemilla-Anbau',b:'<span class="lex-term">Sinsemilla-Anbau</span><span class="lex-tag bio">Anbau</span><br>Durch fr\u00fchzeitiges Entfernen m\u00e4nnlicher Pflanzen bleiben weibliche Bl\u00fcten unbefruchtet und produzieren mehr Harz statt Samen. Heute Standardpraxis f\u00fcr hochwertigen Anbau. Einzelne \u00fcbersehene M\u00e4nnchen k\u00f6nnen eine gesamte Ernte durch unerw\u00fcnschte Best\u00e4ubung beeintr\u00e4chtigen.'}
  ]},
  medizin:{cat:'Medizin & Pharmazie',items:[
    {t:'Dronabinol',b:'<span class="lex-term">Dronabinol</span><span class="lex-tag med">Pharmazie</span><br>Dronabinol ist der internationale Freiname f\u00fcr pharmazeutisch reines THC. Eingesetzt bei chemotherapiebedingter \u00dcbelkeit und Appetitverlust bei HIV/AIDS. Da es reines THC ohne andere Cannabinoide enth\u00e4lt, fehlt der Entourage-Effekt \u2014 Nebenwirkungen wie Angst oder Dysphorie treten h\u00e4ufiger auf als bei Vollspektrum-Pr\u00e4paraten. In Deutschland als Rezeptursubstanz verschreibungsf\u00e4hig.'},
    {t:'Sativex (Nabiximols)',b:'<span class="lex-term">Sativex</span><span class="lex-tag med">Pharmazie</span><br>Sativex ist ein standardisierter Cannabisvollextrakt als Mundspray mit einem THC:CBD-Verh\u00e4ltnis von etwa 1:1. Zugelassen zur Behandlung von Spastik bei Multipler Sklerose. In der Schweiz, Deutschland und \u00d6sterreich auf Rezept erh\u00e4ltlich.'},
    {t:'Epidiolex',b:'<span class="lex-term">Epidiolex</span><span class="lex-tag med">Pharmazie</span><br>Epidiolex ist pharmazeutisch reines CBD, zugelassen f\u00fcr schwere Epilepsieformen (Dravet-Syndrom, Lennox-Gastaut-Syndrom) bei Kindern. Erstes von FDA und EMA zugelassenes cannabisbasiertes Medikament. Die genaue Wirkungsweise l\u00e4uft nicht \u00fcber CB1/CB2-Rezeptoren.'},
    {t:'Nabilon (Canemes)',b:'<span class="lex-term">Nabilon</span><span class="lex-tag med">Pharmazie</span><br>Nabilon ist ein vollsynthetischer THC-Abk\u00f6mmling in Kapselform, st\u00e4rker psychoaktiv als Dronabinol. Eingesetzt bei chemotherapiebedingter \u00dcbelkeit, wenn andere Mittel versagen. Wegen des h\u00f6heren Missbrauchspotenzials strenger reguliert.'},
    {t:'Medizinalbl\u00fcten (Apothekensorten)',b:'<span class="lex-term">Medizinalbl\u00fcten</span><span class="lex-tag med">Pharmazie</span><br>Seit der Legalisierung in Deutschland (2017) und Schweizer Pilotversuchen sind standardisierte Cannabisbl\u00fcten auf Rezept erh\u00e4ltlich. Sorten: Bedrocan (22% THC, <1% CBD), Bediol (6,3% THC, 8% CBD), Bedrolite (<1% THC, 9% CBD). Gehalt, Qualit\u00e4t und Reinheit sind GMP-zertifiziert \u2014 im Gegensatz zu Schwarzmarkt-Ware.'}
  ]},
  risiken:{cat:'Physiologie & Risiken',items:[
    {t:'Toleranzentwicklung',b:'<span class="lex-term">Toleranz</span><span class="lex-tag adv">Risiko</span><br>Regelm\u00e4ssiger Cannabiskonsum f\u00fchrt zur Downregulation von CB1-Rezeptoren \u2014 das Gehirn reduziert die Anzahl verf\u00fcgbarer Andockstellen. Folge: F\u00fcr denselben Effekt werden h\u00f6here Dosen ben\u00f6tigt. Toleranz baut sich in Wochen auf und nach einer Pause (T-Break) innerhalb von 2\u20134 Wochen wieder ab. Stark gestiegener Bedarf ist ein Warnsignal f\u00fcr ein problematisches Konsummuster.'},
    {t:'Cannabis-Use-Disorder (CUD)',b:'<span class="lex-term">CUD</span><span class="lex-tag adv">Risiko</span><br>Cannabisabh\u00e4ngigkeit betrifft sch\u00e4tzungsweise 9% aller Konsumenten, bei t\u00e4glichem Konsum bis zu 50%. Kriterien: Kontrollverlust, Vernachl\u00e4ssigung anderer Aktivit\u00e4ten, Konsum trotz negativer Konsequenzen. K\u00f6rperliche Entzugssymptome (Reizbarkeit, Schlafst\u00f6rungen, Appetitlosigkeit) dauern 1\u20132 Wochen. Professionelle Hilfe ist effektiv.'},
    {t:'Amotivationssyndrom',b:'<span class="lex-term">Amotivationssyndrom</span><span class="lex-tag adv">Risiko</span><br>Anhaltende Antriebslosigkeit, Apathie und verminderte Leistungsf\u00e4higkeit bei chronischen Konsumenten. Ob direkter Cannabiseffekt oder Folge vorbestehender psychischer Erkrankungen ist wissenschaftlich umstritten. Beobachtet hauptso bei t\u00e4glichem Konsum \u00fcber l\u00e4ngere Zeitr\u00e4ume, besonders bei Konsumbeginn im Jugendalter. Abstinenz f\u00fchrt meist zur Erholung.'},
    {t:'Cannabinoid-Hyperemesis-Syndrom (CHS)',b:'<span class="lex-term">CHS</span><span class="lex-tag adv">Risiko</span><br>Paradoxes Syndrom bei langj\u00e4hrigen starken Konsumenten: zyklisches Erbrechen und starke Bauchkr\u00e4mpfe trotz der normalerweise brechreizlindernden Wirkung von Cannabis. Typisch: vorl\u00e4ufige Linderung durch heisses Duschen. Einzige wirksame Behandlung: vollst\u00e4ndige Cannabisabstinenz. H\u00e4ufig fehldiagnostiziert.'},
    {t:'Greening Out (\u00dcberdosierung)',b:'<span class="lex-term">Greening Out</span><span class="lex-tag adv">\u00dcberdosierung</span><br>Akute Cannabis-\u00dcberdosierung mit Panikattacken, starkem Herzrasen, \u00dcbelkeit, Dissoziation und Benommenheit. H\u00e4ufigste Ursachen: zu hohe Dosis, Edibles (verz\u00f6gerter Onset), unerfahrene Konsumenten. Cannabis allein ist nicht letal. Erste Hilfe: ruhige Umgebung, Traubenzucker, hinlegen, beruhigende Ansprache. Nicht allein lassen.'},
    {t:'Psychose-Risiko',b:'<span class="lex-term">Psychose-Risiko</span><span class="lex-tag adv">Risiko</span><br>Hochdosierter regelm\u00e4ssiger THC-Konsum erh\u00f6ht das Risiko f\u00fcr cannabis-induzierte Psychosen und kann bei genetisch Pr\u00e4disponierten Schizophrenie ausl\u00f6sen oder beschleunigen. Risiko bei Konsumbeginn unter 18 Jahren besonders erh\u00f6ht. High-potency-Produkte (\u00fcber 20% THC) und t\u00e4glicher Konsum sind die gr\u00f6ssten Risikofaktoren. CBD wirkt dem antipsychotischen Effekt entgegen.'}
  ]},
  szene:{cat:'Szene & Geschichte',items:[
    {t:'Slang & Umgangssprache',b:'<span class="lex-term">Slang</span><br>Cannabis ist weltweit unter Hunderten Slang-Begriffen bekannt. Deutschsprachig: Gras, Weed, Stoff, Dope, Shit. Englisch: Pot, Mary Jane, Herb, Reefer, Bud. Spanisch: Hierba, Maria, Mota. Die Vielfalt der Begriffe spiegelt die globale Verbreitung und subkulturelle Bedeutung wider.'},
    {t:'Haschisch-Traditionen weltweit',b:'<span class="lex-term">Haschisch-Traditionen</span><span class="lex-tag base">Historisch</span><br>Cannabis hat eine jahrtausendealte Kulturgeschichte. Charas (Indien/Nepal), Kif (Marokko), Dagga (S\u00fcdafrika) und Bhang (Indien) sind regionale Zubereitungsformen mit religi\u00f6sem oder kulturellem Kontext. Traditionelle Edibles wie Majun (arabische Welt), Dawamesch und Esrar (T\u00fcrkei) enthalten Cannabis in s\u00fcssen Pasten \u2014 teils seit Jahrhunderten in rituellen oder medizinischen Kontexten verwendet.'},
    {t:'Reefer Madness (historisch)',b:'<span class="lex-term">Reefer Madness</span><span class="lex-tag base">Historisch</span><br>\\"Reefer Madness\\" war ein US-Propagandafilm aus 1936, der Cannabis als Ausl\u00f6ser von Mord und Wahnsinn darstellte. Er steht exemplarisch f\u00fcr die politisch motivierte Kriminalisierung von Cannabis in den 1930er Jahren \u2014 vorangetrieben durch Harry Anslinger. Der Film hat heute Kultstatus als Paradebeispiel f\u00fcr Drogenpropaganda.'},
    {t:'Entourage-Effekt',b:'<span class="lex-term">Entourage-Effekt</span><span class="lex-tag base">Konzept</span><br>Cannabinoide, Terpene und Flavonoide wirken zusammen st\u00e4rker und ausgewogener als isoliert. Reines THC (Dronabinol) zeigt oft mehr Nebenwirkungen als Vollspektrum-Cannabis. CBD kann die angstausl\u00f6sende Wirkung von THC abschw\u00e4chen. Wichtiges Argument f\u00fcr Vollspektrum-Extrakte gegen\u00fcber isolierten Cannabinoiden \u2014 besonders f\u00fcr medizinische Anwender.'}
  ]}"""
    src = src.replace(OLD_END, "THCA\u2192THC, CBDA\u2192CBD durch Hitze. Pflicht f\u00fcr alle Edibles.'}\n  ]}" + NEW_CATS + "\n};")
    changes += 1; print('\u2714 [4] 9 neue Kategorien eingef\u00fcgt')
else:
    print('\u2718 [4] Einf\u00fcgestelle nicht gefunden!')

# ── Speichern & Verifikation ──────────────────────────────────────────────
print(f'\n{changes}/4 \u00c4nderungen.')
open('index.html', 'w', encoding='utf-8').write(src)
print('Datei gespeichert.')

scripts = re.findall(r'<script(?![^>]*src)[^>]*>(.*?)</script>', src, re.DOTALL)
for i, s in enumerate(scripts):
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False, encoding='utf-8') as f:
        f.write(s); tmp = f.name
    r = subprocess.run(['node', '--check', tmp], capture_output=True, text=True)
    os.unlink(tmp)
    if r.returncode == 0:
        print(f'\u2714 Script-Block {i}: Syntax OK')
    else:
        m2 = re.search(r':(\d+)\n', r.stderr)
        ln = int(m2.group(1)) if m2 else '?'
        lines = s.split('\n')
        print(f'\u2718 Script-Block {i}, Zeile {ln}: {repr(lines[int(ln)-1][:100]) if isinstance(ln,int) else ""}')
        sys.exit(1)
print('\n\u2705 Fertig \u2014 git add index.html && git commit -m "Lexikon v1.0: 9 neue Kategorien, ~65 Eintr\u00e4ge" && git push')
